

## Product & Review Dataset Creation

In [ ]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 300)

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [2]:
df = pd.read_csv("../processed/amazon_products_cleaned.csv")

print("Dataset Loaded")

Dataset Loaded

In [4]:
df.head(2)

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,review_title,review_content,img_link,category_list,num_categories,discount_amount,price_bucket,review_length,description_length,product_name_length,review_word_count,description_word_count,popularity_score,price_per_rating,price_per_rating_inf,search_document
0,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",399.0,1099.0,64.0,4.2,24269,"High Compatibility : Compatible With iPhone 12, 11, X/XsMax/Xr ,iPhone 8/8 Plus,iPhone 7/7 Plus,iPhone 6s/6s Plus,iPhone 6/6 Plus,iPhone 5/5s/5c/se,iPad Pro,iPad Air 1/2,iPad mini 1/2/3,iPod nano7,iPod touch and more apple devices.|Fast Charge&Data Sync : It can charge and sync simultaneously at...","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good","Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/W/WEBP_402378-T1/images/...",https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51UsScvHQNL._SX300_SY300_QL70_FMwebp_.jpg,"['Computers&Accessories', 'Accessories&Peripherals', 'Cables&Accessories', 'Cables', 'USBCables']",5,700.0,Very Cheap,483,960,162,60,132,42.407384,95.00,95.00,"\nProduct Name:\nWayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)\n\nProduct Description:\nHigh Compatibility : Compatible With iPhone 12, 11, X/XsMax/Xr ,iPhone 8/8 Plus,iPhone 7/7 ..."
1,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)",199.0,349.0,43.0,4.0,43994,"Compatible with all Type C enabled devices, be it an android smartphone (Mi, Samsung, Oppo, Vivo, Realme, OnePlus, etc), tablet, laptop (Macbook, Chromebook, etc)|Supports Quick Charging (2.0/3.0)|Unbreakable – Made of special braided outer with rugged interior bindings, it is ultra-durable cabl...","A Good Braided Cable for Your Type C Device,Good quality product from ambrane,Super cable,As,Good quality,Good product,its good,Good quality for the price but one issue with my unit",I ordered this cable to connect my phone to Android Auto of car. The cable is really strong and the connection ports are really well made. I already has a Micro USB cable from Ambrane and it's still in good shape. I connected my phone to the car using the cable and it got connected well and no i...,https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/31zOsqQOAOL._SY445_SX342_QL70_FMwebp_.jpg,"['Computers&Accessories', 'Accessories&Peripherals', 'Cables&Accessories', 'Cables', 'USBCables']",5,150.0,Very Cheap,1186,605,193,201,93,42.767325,49.75,49.75,"\nProduct Name:\nAmbrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)\n\nProduct Description:\nCompatible with all Type C enabled devices, be it an android..."

In [5]:
print(df.shape)

(1465, 24)

In [6]:
duplicate_products = df["product_id"].duplicated().sum()

print("Duplicate Product IDs :", duplicate_products)

Duplicate Product IDs : 114

In [7]:
print("Total Rows :", len(df))

print("Unique Products :", df["product_id"].nunique())

print("Total Reviews :", len(df))

Total Rows : 1465
Unique Products : 1351
Total Reviews : 1465

In [8]:
review_count = (
    df.groupby("product_id")
      .size()
      .sort_values(ascending=False)
)

review_count.head(10)

product_id
B077Z65HSD    3
B09KLVMZ3B    3
B098NS6PVG    3
B083342NKJ    3
B082T6V3DT    3
B08Y1TFSP6    3
B09C6HXFC1    3
B08HDJ86NZ    3
B09CMP1SC8    3
B085DTN6R2    3
dtype: int64

In [9]:
products = (
    df
    .sort_values("product_id")
    .drop_duplicates(
        subset="product_id",
        keep="first"
    )
    .reset_index(drop=True)
)

In [10]:
products.shape

(1351, 24)

In [11]:
products.head(2)

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,review_title,review_content,img_link,category_list,num_categories,discount_amount,price_bucket,review_length,description_length,product_name_length,review_word_count,description_word_count,popularity_score,price_per_rating,price_per_rating_inf,search_document
0,B002PD61Y4,D-Link DWA-131 300 Mbps Wireless Nano USB Adapter (Black),507.0,1208.0,58.0,4.1,8131,Connects your computer to a high-speed wireless network|Supports WPA/WPA2 wireless encryption to help prevent outside intrusion and protect your personal information from being exposed.|3 Year Brand Warranty|2.4Ghz frequency band (300mbps)|2 fixed internal Wi-Fi antenna|N300 MIMO Wi-Fi USB Adapt...,"good tool to use for,Brand is always good,Overall good and a better experience,It is useful to me.,Works well with cpplus dvr,Good,Its not plug an play u need to install the driver and will support till 2.4 Ghz not above that,Surveillance Camera In My House","good quality tool from d linkWiFi signal is good,Nice product,Overall good and a better experience,It funcions properly and useful to me.,I you want to buy it for CP Plus Orange DVR, it works.,Nice,Its not plug an play u need to install the driver and will support till 2.4 Ghz not above that. Im...",https://m.media-amazon.com/images/I/31+NwZ8gb1L._SX300_SY300_.jpg,"['Computers&Accessories', 'NetworkingDevices', 'NetworkAdapters', 'WirelessUSBAdapters']",4,701.0,Very Cheap,483,386,57,88,51,36.914605,123.658537,123.658537,\nProduct Name:\nD-Link DWA-131 300 Mbps Wireless Nano USB Adapter (Black)\n\nProduct Description:\nConnects your computer to a high-speed wireless network|Supports WPA/WPA2 wireless encryption to help prevent outside intrusion and protect your personal information from being exposed.|3 Year Bra...
1,B002SZEOLG,"TP-Link Nano USB WiFi Dongle 150Mbps High Gain Wireless Network Wi-Fi Adapter for PC Desktop and Laptops, Supports Windows 10/8.1/8/7/XP, Linux, Mac OS X (TL-WN722N)",749.0,1339.0,44.0,4.2,179692,"150 Mbps Wi-Fi —— Exceptional wireless speed up to 150Mbps brings best experience for video streaming or internet calls|Easy Set up —— Easy wireless security encryption at a push of the WPS button|Antenna —— 4dBi detachable Omni Directional antenna, remarkably strengthen signal power of the USB ...","Works on linux for me. Get the model with antenna.,Does what it say but other brands available at lesser price,Easy Handle,Great product,Perfect working,Speed is perfect,Great Design, Build, Connectivity Range, Packaging and other features but no linux support since v2,Very good","I use this to connect an old PC to internet. I tried lubuntu 20 and ubuntu 22, it worked out of the box in both, didn't have to do any setup. There's an extender cable so you can place this in a comfortable place. Get the model with antenna because otherwise you'll have range problems if you're ...",https://m.media-amazon.com/images/I/31Wb+A3VVdL._SY300_SX300_.jpg,"['Computers&Accessories', 'NetworkingDevices', 'NetworkAdapters', 'WirelessUSBAdapters']",4,590.0,Very Cheap,3989,607,165,678,93,50.815821,178.333333,178.333333,"\nProduct Name:\nTP-Link Nano USB WiFi Dongle 150Mbps High Gain Wireless Network Wi-Fi Adapter for PC Desktop and Laptops, Supports Windows 10/8.1/8/7/XP, Linux, Mac OS X (TL-WN722N)\n\nProduct Description:\n150 Mbps Wi-Fi —— Exceptional wireless speed up to 150Mbps brings best experience for vi..."

In [16]:
print(df.columns)

Index(['product_id', 'product_name', 'discounted_price', 'actual_price',
       'discount_percentage', 'rating', 'rating_count', 'about_product',
       'review_title', 'review_content', 'img_link', 'category_list',
       'num_categories', 'discount_amount', 'price_bucket', 'review_length',
       'description_length', 'product_name_length', 'review_word_count',
       'description_word_count', 'popularity_score', 'price_per_rating',
       'price_per_rating_inf', 'search_document'],
      dtype='str')

In [17]:
reviews = df[
    [
        "product_id",
        "product_name",
        "review_title",
        "review_content",
        "rating",
        "rating_count",
        "review_length",
        "review_word_count"
    ]
].copy()

reviews.head()

,product_id,product_name,review_title,review_content,rating,rating_count,review_length,review_word_count
0,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good","Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/W/WEBP_402378-T1/images/...",4.2,24269,483,60
1,B098NS6PVG,"Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)","A Good Braided Cable for Your Type C Device,Good quality product from ambrane,Super cable,As,Good quality,Good product,its good,Good quality for the price but one issue with my unit",I ordered this cable to connect my phone to Android Auto of car. The cable is really strong and the connection ports are really well made. I already has a Micro USB cable from Ambrane and it's still in good shape. I connected my phone to the car using the cable and it got connected well and no i...,4.0,43994,1186,201
2,B096MSW6CT,"Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices","Good speed for earlier versions,Good Product,Working good,Good for the price,Good,Worth for money,Working nice,it's a really nice product","Not quite durable and sturdy,https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71rIggrbUCL._SY88.jpg,Working good,https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61bKp9YO6wL._SY88.jpg,Product,Very nice product,Working well,It's a really nice product",3.9,7928,271,13
3,B08HDJ86NZ,"boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)","Good product,Good one,Nice,Really nice product,Very first time change,Good,Fine product but could be better,Very nice it's charging like jet","Good product,long wire,Charges good,Nice,I bought this cable for Rs.339 worthy product for this price, i tested it in various charger adapters 33w and 18w it supports fast charging as well.,Good,Ok,I had got this at good price on sale on Amazon and product is useful with warranty but for warrant...",4.2,94363,443,77
4,B08CF3B7N1,"Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)","As good as original,Decent,Good one for secondary use,Best quality,GOOD,Amazing product at a mind blowing price!,Nice Quality,Good product","Bought this instead of original apple, does the work for 150rs, not as fast as apple charger but its a good option if you want cheap and good product, bought it for iPad pro 10.5 and it's working flawlessly, build quality is ok, its not like i am gonna hang my clothes on it and i want a very str...",4.2,16905,2451,415

In [18]:
print("Review Dataset Shape")
print(reviews.shape)

Review Dataset Shape
(1465, 8)

In [19]:
print("Total Reviews :", len(reviews))

print("Unique Products :", reviews["product_id"].nunique())

Total Reviews : 1465
Unique Products : 1351

In [20]:
reviews[
    [
        "review_title",
        "review_length",
        "review_word_count"
    ]
].head()

,review_title,review_length,review_word_count
0,"Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good",483,60
1,"A Good Braided Cable for Your Type C Device,Good quality product from ambrane,Super cable,As,Good quality,Good product,its good,Good quality for the price but one issue with my unit",1186,201
2,"Good speed for earlier versions,Good Product,Working good,Good for the price,Good,Worth for money,Working nice,it's a really nice product",271,13
3,"Good product,Good one,Nice,Really nice product,Very first time change,Good,Fine product but could be better,Very nice it's charging like jet",443,77
4,"As good as original,Decent,Good one for secondary use,Best quality,GOOD,Amazing product at a mind blowing price!,Nice Quality,Good product",2451,415

In [21]:
avg_rating = (
    reviews
    .groupby("product_id")["rating"]
    .mean()
    .reset_index()
)

avg_rating.rename(
    columns={
        "rating":"average_rating"
    },
    inplace=True
)

avg_rating.head()

   product_id  average_rating
0  B002PD61Y4             4.1
1  B002SZEOLG             4.2
2  B003B00484             4.3
3  B003L62T7W             4.3
4  B004IO5BMQ             4.5

In [22]:
products = products.merge(
    avg_rating,
    on="product_id",
    how="left"
)

products.head()

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,review_title,review_content,img_link,category_list,num_categories,discount_amount,price_bucket,review_length,description_length,product_name_length,review_word_count,description_word_count,popularity_score,price_per_rating,price_per_rating_inf,search_document,average_rating
0,B002PD61Y4,D-Link DWA-131 300 Mbps Wireless Nano USB Adapter (Black),507.0,1208.0,58.0,4.1,8131,Connects your computer to a high-speed wireless network|Supports WPA/WPA2 wireless encryption to help prevent outside intrusion and protect your personal information from being exposed.|3 Year Brand Warranty|2.4Ghz frequency band (300mbps)|2 fixed internal Wi-Fi antenna|N300 MIMO Wi-Fi USB Adapt...,"good tool to use for,Brand is always good,Overall good and a better experience,It is useful to me.,Works well with cpplus dvr,Good,Its not plug an play u need to install the driver and will support till 2.4 Ghz not above that,Surveillance Camera In My House","good quality tool from d linkWiFi signal is good,Nice product,Overall good and a better experience,It funcions properly and useful to me.,I you want to buy it for CP Plus Orange DVR, it works.,Nice,Its not plug an play u need to install the driver and will support till 2.4 Ghz not above that. Im...",https://m.media-amazon.com/images/I/31+NwZ8gb1L._SX300_SY300_.jpg,"['Computers&Accessories', 'NetworkingDevices', 'NetworkAdapters', 'WirelessUSBAdapters']",4,701.0,Very Cheap,483,386,57,88,51,36.914605,123.658537,123.658537,\nProduct Name:\nD-Link DWA-131 300 Mbps Wireless Nano USB Adapter (Black)\n\nProduct Description:\nConnects your computer to a high-speed wireless network|Supports WPA/WPA2 wireless encryption to help prevent outside intrusion and protect your personal information from being exposed.|3 Year Bra...,4.1
1,B002SZEOLG,"TP-Link Nano USB WiFi Dongle 150Mbps High Gain Wireless Network Wi-Fi Adapter for PC Desktop and Laptops, Supports Windows 10/8.1/8/7/XP, Linux, Mac OS X (TL-WN722N)",749.0,1339.0,44.0,4.2,179692,"150 Mbps Wi-Fi —— Exceptional wireless speed up to 150Mbps brings best experience for video streaming or internet calls|Easy Set up —— Easy wireless security encryption at a push of the WPS button|Antenna —— 4dBi detachable Omni Directional antenna, remarkably strengthen signal power of the USB ...","Works on linux for me. Get the model with antenna.,Does what it say but other brands available at lesser price,Easy Handle,Great product,Perfect working,Speed is perfect,Great Design, Build, Connectivity Range, Packaging and other features but no linux support since v2,Very good","I use this to connect an old PC to internet. I tried lubuntu 20 and ubuntu 22, it worked out of the box in both, didn't have to do any setup. There's an extender cable so you can place this in a comfortable place. Get the model with antenna because otherwise you'll have range problems if you're ...",https://m.media-amazon.com/images/I/31Wb+A3VVdL._SY300_SX300_.jpg,"['Computers&Accessories', 'NetworkingDevices', 'NetworkAdapters', 'WirelessUSBAdapters']",4,590.0,Very Cheap,3989,607,165,678,93,50.815821,178.333333,178.333333,"\nProduct Name:\nTP-Link Nano USB WiFi Dongle 150Mbps High Gain Wireless Network Wi-Fi Adapter for PC Desktop and Laptops, Supports Windows 10/8.1/8/7/XP, Linux, Mac OS X (TL-WN722N)\n\nProduct Description:\n150 Mbps Wi-Fi —— Exceptional wireless speed up to 150Mbps brings best experience for vi...",4.2
2,B003B00484,Duracell Plus AAA Rechargeable Batteries (750 mAh) Pack of 4,399.0,499.0,20.0,4.3,27201,"Duracell Rechargeable AAA 750mAh batteries stay charged for up to 12 months, when not in use|Unused Duracell Rechargeable AAA 750mAh batteries are guaranteed to last 3 years|Duracell Rechargeable AAA 750mAh batteries come pre-charged, ready to use|Duracell Rechargeable AAA 750mAh batteries can b...","Works Good,Perfect replacement cell for trimmer,Wow,As they said in ad worth it,A good product,Fit for phillips trimmer.,Good,Good Product","Works good,Bought it to replace my Phillips QT4005 trimmer's 7yr old battery cell.Old trimmer battery lost it torque... would not start without smacking it on the hand.Soldering the connections was bit tricky but i got it done by sanding both side surfaces of the new battery cell.New Duracell o...",https://m.media-amazon.com/images/I/418YrbHVLCL._SX300_SY300_QL70_FMwebp_.jpg,"['Electronics', 'GeneralPurposeBatteries&BatteryChargers', 'RechargeableBatteries']",3,100.0,Very Cheap,1060,470,60,159,68,43.907497,92.790698,92.790698,"\nProduct Name:\nDuracell Plus AAA Rechargeable Batteries (750 mAh) Pack of 4\n\nProduct Description:\nDuracell Rechargeable AAA 750mAh batteries stay charged for up to 12 months, when not in use|Unused Duracell Rechargeable AAA 750mAh batteries are guaranteed to last 3 years|Duracell Rechargeab...",4.3
3,B003L62T7W,"Logitech B100 Wired USB Mouse, 3 yr Warranty, 800 DPI Optical Tracking, Ambidextrous PC/Mac/Laptop - Black",279.0,375.0,26.0,4.3,31534,"A comfortable, ambidextrous shape feels good in either hand, so you feel more comfortable as you work-even at the end of the day.|With 800 dpi sensitivity, you'll get precise cursor control so you can edit documents and navigate the Web more efficiently.|Side-to-side scrolling plus zoom lets you...","Handy Mouse,Good quality mouse,Good one.,Good,Good cheap reliable,Gud quality mouse,Very comfortable,Quality + Less Price Makes it Best to buy.","Liked this Product,https://m.media-amazon.com/images/I/710C5jPDcrL._SY88.jpg,Purchased for a laptop. Perfectly working,Good,Very good mouse for a budget setup.,usefull . ... gud quality,The good thing about this mouse is that u can remove the scrolling clip attached inside the scrolling wheel an...",https://m.media-amazon.com/images/I/31iFF1KbkpL._SX300_SY300_QL70_FMwebp_.jpg,"['Computers&Accessories', 'Accessories&Peripherals', 'Keyboards,Mice&InputDevices', 'Mice']",4,96.0,Very Cheap,635,702,106,95,112,44.543069,64.883721,64.883721,"\nProduct Name:\nLogitech B100 Wired USB Mouse, 3 yr Warranty, 800 DPI Optical Tracking, Ambidextrous PC/Mac/Laptop - Black\n\nProduct Description:\nA comfortable, ambidextrous shape feels good in either hand, so you feel more comfortable as you work-even at the end of the day.|With 800 dpi sens...",4.3
4,B004IO5BMQ,"Logitech M235 Wireless Mouse, 1000 DPI Optical Tracking, 12 Month Life Battery, Compatible with Windows, Mac, Chromebook/PC/Laptop",699.0,995.0,30.0,4.5,54405,"You can surf the Web with more comfort and ease—thanks to the contoured design with soft rubber grips. And your mouse is easy to slip into a bag when you want to take it with you.|You’ll enjoy smooth cursor control, precise tracking and easy text selection on the surfaces where you use your comp...","Good silent mouse,Too small to hold!,Reviewing after 8 months of with battery backup review,Its very small do take note of that,** Nice product,Good product,Good Buy for normal use in office,Stylish mouse","It's little small for big hands. But best available in the market.,Good product, but too smaller than the regular one!,Hello everyone,I bought this Mouse in April 2022, so after 8 months of use, I'm writing this review.Battery (the most important one): 10/10 - It came with a single AA-sized batt...",https://m.media-amazon.com/images/I/31CtVvtFt+L._SY300_SX300_.jpg,"['Computers&Accessories', 'Accessories&Peripherals', 'Keyboards,Mice&InputDevices', 'Mice']",4,296.0,Very Cheap,1730,783,130,300,127,49.069034,155.333333,155.333333,"\nProduct Name:\nLogitech M235 Wireless Mouse, 1000 DPI Optical Tracking, 12 Month Life Battery, Compatible with Windows, Mac, Chromebook/PC/Laptop\n\nProduct Description:\nYou can surf the Web with more comfort and ease—thanks to the contoured design with soft rubber grips. And your mouse is ea...",4.5

In [23]:
review_count = (
    reviews
    .groupby("product_id")
    .size()
    .reset_index(name="total_reviews")
)

review_count.head()

   product_id  total_reviews
0  B002PD61Y4              2
1  B002SZEOLG              1
2  B003B00484              1
3  B003L62T7W              1
4  B004IO5BMQ              1

In [24]:
products = products.merge(
    review_count,
    on="product_id",
    how="left"
)

products.head()

,product_id,product_name,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,review_title,review_content,img_link,category_list,num_categories,discount_amount,price_bucket,review_length,description_length,product_name_length,review_word_count,description_word_count,popularity_score,price_per_rating,price_per_rating_inf,search_document,average_rating,total_reviews
0,B002PD61Y4,D-Link DWA-131 300 Mbps Wireless Nano USB Adapter (Black),507.0,1208.0,58.0,4.1,8131,Connects your computer to a high-speed wireless network|Supports WPA/WPA2 wireless encryption to help prevent outside intrusion and protect your personal information from being exposed.|3 Year Brand Warranty|2.4Ghz frequency band (300mbps)|2 fixed internal Wi-Fi antenna|N300 MIMO Wi-Fi USB Adapt...,"good tool to use for,Brand is always good,Overall good and a better experience,It is useful to me.,Works well with cpplus dvr,Good,Its not plug an play u need to install the driver and will support till 2.4 Ghz not above that,Surveillance Camera In My House","good quality tool from d linkWiFi signal is good,Nice product,Overall good and a better experience,It funcions properly and useful to me.,I you want to buy it for CP Plus Orange DVR, it works.,Nice,Its not plug an play u need to install the driver and will support till 2.4 Ghz not above that. Im...",https://m.media-amazon.com/images/I/31+NwZ8gb1L._SX300_SY300_.jpg,"['Computers&Accessories', 'NetworkingDevices', 'NetworkAdapters', 'WirelessUSBAdapters']",4,701.0,Very Cheap,483,386,57,88,51,36.914605,123.658537,123.658537,\nProduct Name:\nD-Link DWA-131 300 Mbps Wireless Nano USB Adapter (Black)\n\nProduct Description:\nConnects your computer to a high-speed wireless network|Supports WPA/WPA2 wireless encryption to help prevent outside intrusion and protect your personal information from being exposed.|3 Year Bra...,4.1,2
1,B002SZEOLG,"TP-Link Nano USB WiFi Dongle 150Mbps High Gain Wireless Network Wi-Fi Adapter for PC Desktop and Laptops, Supports Windows 10/8.1/8/7/XP, Linux, Mac OS X (TL-WN722N)",749.0,1339.0,44.0,4.2,179692,"150 Mbps Wi-Fi —— Exceptional wireless speed up to 150Mbps brings best experience for video streaming or internet calls|Easy Set up —— Easy wireless security encryption at a push of the WPS button|Antenna —— 4dBi detachable Omni Directional antenna, remarkably strengthen signal power of the USB ...","Works on linux for me. Get the model with antenna.,Does what it say but other brands available at lesser price,Easy Handle,Great product,Perfect working,Speed is perfect,Great Design, Build, Connectivity Range, Packaging and other features but no linux support since v2,Very good","I use this to connect an old PC to internet. I tried lubuntu 20 and ubuntu 22, it worked out of the box in both, didn't have to do any setup. There's an extender cable so you can place this in a comfortable place. Get the model with antenna because otherwise you'll have range problems if you're ...",https://m.media-amazon.com/images/I/31Wb+A3VVdL._SY300_SX300_.jpg,"['Computers&Accessories', 'NetworkingDevices', 'NetworkAdapters', 'WirelessUSBAdapters']",4,590.0,Very Cheap,3989,607,165,678,93,50.815821,178.333333,178.333333,"\nProduct Name:\nTP-Link Nano USB WiFi Dongle 150Mbps High Gain Wireless Network Wi-Fi Adapter for PC Desktop and Laptops, Supports Windows 10/8.1/8/7/XP, Linux, Mac OS X (TL-WN722N)\n\nProduct Description:\n150 Mbps Wi-Fi —— Exceptional wireless speed up to 150Mbps brings best experience for vi...",4.2,1
2,B003B00484,Duracell Plus AAA Rechargeable Batteries (750 mAh) Pack of 4,399.0,499.0,20.0,4.3,27201,"Duracell Rechargeable AAA 750mAh batteries stay charged for up to 12 months, when not in use|Unused Duracell Rechargeable AAA 750mAh batteries are guaranteed to last 3 years|Duracell Rechargeable AAA 750mAh batteries come pre-charged, ready to use|Duracell Rechargeable AAA 750mAh batteries can b...","Works Good,Perfect replacement cell for trimmer,Wow,As they said in ad worth it,A good product,Fit for phillips trimmer.,Good,Good Product","Works good,Bought it to replace my Phillips QT4005 trimmer's 7yr old battery cell.Old trimmer battery lost it torque... would not start without smacking it on the hand.Soldering the connections was bit tricky but i got it done by sanding both side surfaces of the new battery cell.New Duracell o...",https://m.media-amazon.com/images/I/418YrbHVLCL._SX300_SY300_QL70_FMwebp_.jpg,"['Electronics', 'GeneralPurposeBatteries&BatteryChargers', 'RechargeableBatteries']",3,100.0,Very Cheap,1060,470,60,159,68,43.907497,92.790698,92.790698,"\nProduct Name:\nDuracell Plus AAA Rechargeable Batteries (750 mAh) Pack of 4\n\nProduct Description:\nDuracell Rechargeable AAA 750mAh batteries stay charged for up to 12 months, when not in use|Unused Duracell Rechargeable AAA 750mAh batteries are guaranteed to last 3 years|Duracell Rechargeab...",4.3,1
3,B003L62T7W,"Logitech B100 Wired USB Mouse, 3 yr Warranty, 800 DPI Optical Tracking, Ambidextrous PC/Mac/Laptop - Black",279.0,375.0,26.0,4.3,31534,"A comfortable, ambidextrous shape feels good in either hand, so you feel more comfortable as you work-even at the end of the day.|With 800 dpi sensitivity, you'll get precise cursor control so you can edit documents and navigate the Web more efficiently.|Side-to-side scrolling plus zoom lets you...","Handy Mouse,Good quality mouse,Good one.,Good,Good cheap reliable,Gud quality mouse,Very comfortable,Quality + Less Price Makes it Best to buy.","Liked this Product,https://m.media-amazon.com/images/I/710C5jPDcrL._SY88.jpg,Purchased for a laptop. Perfectly working,Good,Very good mouse for a budget setup.,usefull . ... gud quality,The good thing about this mouse is that u can remove the scrolling clip attached inside the scrolling wheel an...",https://m.media-amazon.com/images/I/31iFF1KbkpL._SX300_SY300_QL70_FMwebp_.jpg,"['Computers&Accessories', 'Accessories&Peripherals', 'Keyboards,Mice&InputDevices', 'Mice']",4,96.0,Very Cheap,635,702,106,95,112,44.543069,64.883721,64.883721,"\nProduct Name:\nLogitech B100 Wired USB Mouse, 3 yr Warranty, 800 DPI Optical Tracking, Ambidextrous PC/Mac/Laptop - Black\n\nProduct Description:\nA comfortable, ambidextrous shape feels good in either hand, so you feel more comfortable as you work-even at the end of the day.|With 800 dpi sens...",4.3,1
4,B004IO5BMQ,"Logitech M235 Wireless Mouse, 1000 DPI Optical Tracking, 12 Month Life Battery, Compatible with Windows, Mac, Chromebook/PC/Laptop",699.0,995.0,30.0,4.5,54405,"You can surf the Web with more comfort and ease—thanks to the contoured design with soft rubber grips. And your mouse is easy to slip into a bag when you want to take it with you.|You’ll enjoy smooth cursor control, precise tracking and easy text selection on the surfaces where you use your comp...","Good silent mouse,Too small to hold!,Reviewing after 8 months of with battery backup review,Its very small do take note of that,** Nice product,Good product,Good Buy for normal use in office,Stylish mouse","It's little small for big hands. But best available in the market.,Good product, but too smaller than the regular one!,Hello everyone,I bought this Mouse in April 2022, so after 8 months of use, I'm writing this review.Battery (the most important one): 10/10 - It came with a single AA-sized batt...",https://m.media-amazon.com/images/I/31CtVvtFt+L._SY300_SX300_.jpg,"['Computers&Accessories', 'Accessories&Peripherals', 'Keyboards,Mice&InputDevices', 'Mice']",4,296.0,Very Cheap,1730,783,130,300,127,49.069034,155.333333,155.333333,"\nProduct Name:\nLogitech M235 Wireless Mouse, 1000 DPI Optical Tracking, 12 Month Life Battery, Compatible with Windows, Mac, Chromebook/PC/Laptop\n\nProduct Description:\nYou can surf the Web with more comfort and ease—thanks to the contoured design with soft rubber grips. And your mouse is ea...",4.5,1

In [25]:
products[
    [
        "product_name",
        "average_rating",
        "total_reviews"
    ]
].head()

,product_name,average_rating,total_reviews
0,D-Link DWA-131 300 Mbps Wireless Nano USB Adapter (Black),4.1,2
1,"TP-Link Nano USB WiFi Dongle 150Mbps High Gain Wireless Network Wi-Fi Adapter for PC Desktop and Laptops, Supports Windows 10/8.1/8/7/XP, Linux, Mac OS X (TL-WN722N)",4.2,1
2,Duracell Plus AAA Rechargeable Batteries (750 mAh) Pack of 4,4.3,1
3,"Logitech B100 Wired USB Mouse, 3 yr Warranty, 800 DPI Optical Tracking, Ambidextrous PC/Mac/Laptop - Black",4.3,1
4,"Logitech M235 Wireless Mouse, 1000 DPI Optical Tracking, 12 Month Life Battery, Compatible with Windows, Mac, Chromebook/PC/Laptop",4.5,1

In [26]:
products.isnull().sum()

product_id                0
product_name              0
discounted_price          0
actual_price              0
discount_percentage       0
rating                    0
rating_count              0
about_product             0
review_title              0
review_content            0
img_link                  0
category_list             0
num_categories            0
discount_amount           0
price_bucket              0
review_length             0
description_length        0
product_name_length       0
review_word_count         0
description_word_count    0
popularity_score          0
price_per_rating          0
price_per_rating_inf      0
search_document           0
average_rating            0
total_reviews             0
dtype: int64

In [27]:
reviews.isnull().sum()

product_id           0
product_name         0
review_title         0
review_content       0
rating               0
rating_count         0
review_length        0
review_word_count    0
dtype: int64

In [28]:
memory = (
    products.memory_usage(deep=True).sum()
    /
    (1024*1024)
)

print(f"Memory Usage : {memory:.2f} MB")

Memory Usage : 7.07 MB

In [29]:
products.to_csv(
    "../processed/amazon_products_unique.csv",
    index=False
)

print("Products Dataset Saved")

Products Dataset Saved

In [30]:
reviews.to_csv(
    "../processed/amazon_reviews.csv",
    index=False
)

print("Review Dataset Saved")

Review Dataset Saved